# Generated by Django 4.2.18 on 2025-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_after_pictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='after_pictures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='before_pictures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='service_pictures/'),
        ),
    ]
