# Generated by Django 4.2.18 on 2025-02-08 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_after_pictures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('hotels', 'Hotels'), ('restaurants', 'Restaurants'), ('residential', 'Residential')], default=None, max_length=15),
        ),
    ]
